[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
keypair_vs_pda = "2FRrUXHWvWZFzHCrgTjT5wiG3gRQEC8kP5u56DPvfPQe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
